server:
  port: 8080

spring:
  application:
    name: ticketochoks
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/devdb}
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:devpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: hibernate.format_sql=true
