-- ========== TABLES ==========

CREATE TABLE venue_layout (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    rows INTEGER NOT NULL,
    seats_per_row INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE event (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    ticket_price INTEGER NOT NULL CHECK (ticket_price >= 0),
    start_date_time TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_date_time TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    timezone VARCHAR(255) NOT NULL,
    venue_layout_id BIGINT NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT event_venue_layout_id_key UNIQUE (venue_layout_id)
);

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE role (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE seat (
     id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     row_number INTEGER NOT NULL,
     seat_number INTEGER NOT NULL,
     status VARCHAR(255) CHECK (status IN ('AVAILABLE', 'RESERVED', 'PURCHASED')),
     event_id BIGINT NOT NULL,
     created_at TIMESTAMP(6),
     updated_at TIMESTAMP(6),
     created_by VARCHAR(255),
     updated_by VARCHAR(255)
);

CREATE TABLE ticket (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    seat_id BIGINT,
    user_id BIGINT,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PURCHASED', 'CANCELLED')),
    purchase_date_time TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- ========== FOREIGN KEYS ==========

ALTER TABLE event
    ADD CONSTRAINT fk_event_venue_layout FOREIGN KEY (venue_layout_id) REFERENCES venue_layout(id);

ALTER TABLE seat
    ADD CONSTRAINT fk_seat_event FOREIGN KEY (event_id) REFERENCES event(id);

ALTER TABLE ticket
    ADD CONSTRAINT fk_ticket_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ticket
    ADD CONSTRAINT fk_ticket_seat FOREIGN KEY (seat_id) REFERENCES seat(id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role(id);
